/*
 * Group members:
 * Tam King Man 1155160072
 * Tsang Ho Yin 1155159307
 * Ng Yuk Fung 1155176966
 * Leung Ka Lun 1155157403
 * O Ching Lam 1155159131
 */

// This is a temporary function for testing, the functions are mainly generated by AI

const UserHandler = require('./userhandler');
const { hashPassword } = require('./utils');

async function testUserFunctions() {

    // Assume we have logged in as a user

    const user = {
        userID: 5,
        username: 'hehehe',
        salt: '8770dbbbe87f38421dad27e141f014a9',
        password: '5e24c9d3f42594b5701a4b65a292231971fcab281f63a9c5da4cb12afa2abaaccaac5af2653258af3208f721b748c43114e6cc12bcc3ff8438e337a60f82b810',
        secureqans: '123',
        privacy: 'private',
        description: 'this is a test description',
        active: true,
        usertype: 'user'
      }

    // Create a new user
    const User = new UserHandler(user.userID, user.username, user.salt, user.password, user.usertype, user.privacy, user.active);

    console.log('now start testing!');

    // Test view own profile
    // const profile = await User.viewOwnProfile();
    // console.log(profile)

    // Test update own profile - ["username", "description", "privacy"]
    // const updatedProfile = await User.editProfile(['hehehe', 'this is a test description', 'private']);
    // console.log(updatedProfile)

    // Test view own profile
    // const profile = await User.viewOwnProfile();
    // console.log(profile)

    // Test view other user's profile
    // const otherUser = await User.viewProfile(7);
    // console.log(otherUser)

    // Test follow user
    // const followResult = await User.followUser(7);
    // console.log(followResult)

    // Show all following
    // const following = await User.getFollowing();
    // console.log(following)

    // Test unfollow user
    // const unfollowResult = await User.unfollowUser(7);
    // console.log(unfollowResult)

    // const following2 = await User.getFollowing();
    // console.log(following2)

    // Test secure question
    // const secureResult = await User.checkSecurityAnswer('123');
    // console.log(secureResult)

    // Test reset password
    // const resetResult = await User.resetPassword('sdasdacsdasd');
    // console.log(resetResult)

    // Test send messages
    // const messageResult = await User.sendMessage(5, 'Hello33!');
    // console.log(messageResult)

    // Test receive messages
    // const messageResult = await User.getMessagesWithUser(5);
    // console.log(messageResult)

    // Test noti
    // const notiResult = await User.getNotifications();
    // console.log(notiResult)

    // Test post
    const postResult = await User.createPost('Hello!');
    console.log(postResult)

    console.log('Test ended.')
}

testUserFunctions();