/*
 * Group members:
 * Tam King Man 1155160072
 * Tsang Ho Yin 1155159307
 * Ng Yuk Fung 1155176966
 * Leung Ka Lun 1155157403
 * O Ching Lam 1155159131
 */

// This is a temporary function for testing, the functions are mainly generated by AI

const UserHandler = require('./userhandler');
const { hashPassword } = require('./utils');

async function testUserFunctions() {

    // Assume we have logged in as a user

    // const user = {
    //   userID: 4,
    //   username: 'Kalun',
    //   salt: 'dd391c003d8b186712a9ee26c9f2bb2a',
    //   password: 'ee0227a538176d65ec33d7eacf2f34c05dbffa90ee0750bf696aab3fdf5c7268bd22dc816a20aaf5bf026b1b01ecf08684058a1a76d13656d8caa7c46dbaed0b',
    //   secureqans: '123',
    //   privacy: 'public',
    //   description: null,
    //   active: true,
    //   usertype: 'user'
    // }

    const user = {
    userID: 6,
    username: 'kalun',
    salt: '5a6b2d7cab169a8207698c2607b572ef',
    password: 'd304b6c40cceff3e587c0d333a2d037f5fe9cf2c308b0ad959d26450fbc13a3e2e7a99e6f0477b9053602520ccb1770cb6b6c9994023a5e2dfc8db414d1e8789',
    secureqans: 'kalun',
    privacy: 'public',
    description: null,
    active: true,
    usertype: 'user'
  }

    // Create a new user
    const User = new UserHandler(user.userID, user.username, user.salt, user.password, user.usertype, user.privacy, user.active);

    console.log('now start testing!');

    // Test view own profile
    // const profile = await User.viewOwnProfile();
    // console.log(profile)

    // Test update own profile - ["username", "description", "privacy"]
    // const updatedProfile = await User.editProfile(['hehehe123', 'this is a test description', 'private']);
    // console.log(updatedProfile)

    // Test view own profile
    // const profile = await User.viewOwnProfile();
    // console.log(profile)

    // Test view other user's profile
    // const otherUser = await User.viewProfile(7);
    // console.log(otherUser)

    // Test follow user
    // const followResult = await User.followUser(4);
    // console.log(followResult)

    // Show all following
    // const following = await User.getFollowing();
    // console.log(following)

    // Test unfollow user
    // const unfollowResult = await User.unfollowUser(7);
    // console.log(unfollowResult)

    // const following2 = await User.getFollowing();
    // console.log(following2)

    // Test accept follow request
    // const acceptResult = await User.acceptFollowRequest(6);
    // console.log(acceptResult)

    // Test secure question
    // const secureResult = await User.checkSecurityAnswer('123');
    // console.log(secureResult)

    // Test reset password
    // const resetResult = await User.resetPassword('sdasdacsdasd');
    // console.log(resetResult)

    // Test send messages
    // const messageResult = await User.sendMessage(5, 'Hello33!');
    // console.log(messageResult)

    // Test receive messages
    // const messageResult = await User.getMessagesWithUser(5);
    // console.log(messageResult)

    // Test noti
    // const notiResult = await User.getNotifications();
    // console.log(notiResult)

    // Test create post
    // const postResult = await User.createPost('Hello!');
    // console.log(postResult)

    // Test get all own posts
    // const allPosts = await User.getOwnPosts();
    // console.log(allPosts)

    // Test get all following posts
    const followingPosts = await User.getFollowingPosts();
    console.log(followingPosts)

    // Test delete post
    // const deletePostResult = await User.deletePost(6);
    // console.log(deletePostResult)

    // Test like and unlike post
    // const likePostResult = await User.unlikePost(5);
    // console.log(likePostResult)

    // Test repost
    // const repostResult = await User.repostPost(5);
    // console.log(repostResult)

    // Test comment on a post
    // const commentResult = await User.commentPost(5, 'hehehe');
    // console.log(commentResult)

    // Test like comment
    // const likeCommentResult = await User.likeComment(2);
    // console.log(likeCommentResult)

    // Test unlike comment
    // const unlikeCommentResult = await User.unlikeComment(1);
    // console.log(unlikeCommentResult)

    // Test edit comment
    // const editCommentResult = await User.editComment(4, 'Kalun is the best!');
    // console.log(editCommentResult)

    // Test delete comment
    // const deleteCommentResult = await User.deleteComment(1);
    // console.log(deleteCommentResult)

    console.log('Test ended.')
}

testUserFunctions();