// This is a temporary function for testing, the functions are mainly generated by AI

const AdminHandler = require('./adminhandler');

async function testAdminFunctions() {

  const adminHandler = new AdminHandler();

//   const allUsers = await adminHandler.getAllUsers();
//   console.log('All users:', allUsers);

//   const userID = 1;
//   const user = await adminHandler.getUser(userID);
//   console.log('User:', user);

//   const userIDToDelete = 2; 
//   const deleteUserResult = await adminHandler.deleteUser(userIDToDelete);
//   console.log('User deleted:', deleteUserResult);

    /* The above has been debugged*/


//   const postIDToDelete = 1; 
//   const deletePostResult = await adminHandler.deletePost(postIDToDelete);
//   console.log('Post deleted:', deletePostResult);

//   const commentIDToDelete = 1;
//   const deleteCommentResult = await adminHandler.deleteComment(commentIDToDelete);
//   console.log('Comment deleted:', deleteCommentResult);
}

testAdminFunctions();
